name: Demo

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo Hello

      - name: Current Directory
        run: pwd

      - name: List Files
        run: ls -la
