name: Job Dependency

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - run: echo "Build Complete"

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - run: echo "Testing Complete"

  deploy:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - run: echo "Deployment Complete"
